import { Sanctuary, Trip, TasteProfile } from './types';
import { UNSPLASH_ASSETS } from './unsplash';

export const SEED_SANCTUARIES: Sanctuary[] = [
  {
    id: 'amanemu',
    name: 'Amanemu',
    realm: 'Ise-Shima',
    location: 'Ago Bay, Mie Prefecture, Japan',
    description: 'Natural mineral onsen springs nestled within lush coastal hills, with minimalist cedar pavilions designed by Kerry Hill.',
    curatorNotes: 'Pure architectural stillness. The thermal mineral spring pools at sunset offer absolute solitude.',
    heroImage: UNSPLASH_ASSETS.amanemu.url,
    heroPhotographer: UNSPLASH_ASSETS.amanemu.photographer,
    amenities: ['Private Thermal Onsen', 'Kerry Hill Architecture', 'Ago Bay View', 'Kaiseki Dining'],
    confidenceTier: 'Verified',
    roomType: 'Mori Suite (99 sqm)',
    verifiedInspectionNote: 'Spriha stayed here in March — absolute quietude above Ago Bay.',
    verifiedBy: 'Spriha & Curation Team',
  },
  {
    id: 'benesse-house',
    name: 'Benesse House Oval',
    realm: 'Naoshima',
    location: 'Naoshima Art Island, Seto Inland Sea, Japan',
    description: 'Six private suites wrapped around a reflective water pool on a cliff, designed by Tadao Ando and accessible only by private monorail.',
    curatorNotes: 'Exclusive nighttime access to museum galleries after public visitors depart.',
    heroImage: UNSPLASH_ASSETS.benesseHouse.url,
    heroPhotographer: UNSPLASH_ASSETS.benesseHouse.photographer,
    amenities: ['Tadao Ando Design', 'Private Monorail', '24h Museum Access', 'Sea Terrace'],
    confidenceTier: 'Team-Vetted',
    roomType: 'Oval Room 402',
    verifiedInspectionNote: 'Team-vetted for overnight gallery solitude on Naoshima.',
    verifiedBy: 'TripSpree Curation Team',
  },
  {
    id: 'sowaka',
    name: 'Sowaka Ryokan',
    realm: 'Kyoto',
    location: 'Gion Yasaka, Kyoto, Japan',
    description: 'A restored 100-year-old former tea house combining sukiya-style cedar architecture with private moss courtyards.',
    curatorNotes: 'Unobtrusive hospitality tucked quietly in the historic heart of Gion, steps from Kodai-ji.',
    heroImage: UNSPLASH_ASSETS.sowakaKyoto.url,
    heroPhotographer: UNSPLASH_ASSETS.sowakaKyoto.photographer,
    amenities: ['Hinoki Wood Tubs', 'Moss Courtyards', 'Michelin-starred La Bombance', 'Private Tea Lounge'],
    confidenceTier: 'Verified',
    roomType: 'Sukiya Courtyard Suite',
    verifiedInspectionNote: 'Spriha inspected in March — private courtyard silence steps from Yasaka.',
    verifiedBy: 'TripSpree Curation Team',
  },
  {
    id: 'hoshinoya-kyoto',
    name: 'Hoshinoya Kyoto',
    realm: 'Kyoto',
    location: 'Oi River Gorge, Arashiyama, Japan',
    description: 'Secluded riverside sanctuary accessed solely by a fifteen-minute private wooden riverboat excursion up the Oi River gorge.',
    curatorNotes: 'Centuries-old riverside pavilions enveloped by wild maples and bamboo groves.',
    heroImage: UNSPLASH_ASSETS.hoshinoyaKyoto.url,
    heroPhotographer: UNSPLASH_ASSETS.hoshinoyaKyoto.photographer,
    amenities: ['Private Riverboat Access', 'Water Terrace', 'Woodblock Printing Studio', 'Tea Pavilion'],
    confidenceTier: 'Verified',
    roomType: 'Yamanobe Riverside Room',
    verifiedInspectionNote: 'Wooden boat access verified by curation team in Autumn.',
    verifiedBy: 'TripSpree Curation Team',
  },
];

export const SEED_TRIP: Trip = {
  id: 'kyoto-zen-4d',
  title: 'Autumn Stillness: Kyoto & The Coastal Sanctuaries',
  patronName: 'Julian & Claire Sterling',
  patronEmail: 'patron@tripspree.com',
  realm: 'Western Honshu, Japan',
  status: 'active',
  startDate: '2026-10-14',
  endDate: '2026-10-18',
  curatorName: 'Elena Vance',
  curatorTitle: 'Senior Curator • Kansai & Seto Inland Sea',
  driverName: 'Mr. Tanaka',
  driverCar: 'Black Toyota Alphard Executive Lounge #408',
  driverStandingBy: false,
  days: [
    {
      id: 'day-1',
      dayNumber: 1,
      date: 'OCT 14, 2026',
      title: 'Arrival & The Sukiya Courtyards of Gion',
      destination: 'Kyoto • Gion Yasaka',
      sanctuaryName: 'Sowaka Ryokan',
      morningActivity: {
        time: '11:00 JST',
        title: 'Private Chauffeur Arrival from Kansai International Airport',
        location: 'Kansai Airport -> Sowaka Kyoto',
        notes: 'Luggage forwarded directly to Sukiya Courtyard Suite 108.',
        confidenceTier: 'Verified',
      },
      afternoonActivity: {
        time: '14:30 JST',
        title: 'Unescorted Garden Walk through Kennin-ji Twin Dragon Pavilions',
        location: 'Kennin-ji Zen Temple, Higashiyama',
        notes: 'Private access through the abbot cloister before general afternoon gates close.',
        confidenceTier: 'Verified',
      },
      eveningActivity: {
        time: '19:30 JST',
        title: 'Intimate Kaiseki Dinner at La Bombance Gion',
        location: 'Sowaka Dining Pavilion',
        notes: 'Nine-course seasonal menu highlighting Tamba chestnuts and sweet sea bream.',
        confidenceTier: 'Verified',
      },
      curatorNote: 'Rest after international transit. Tomorrow morning the private wooden boat departs at dawn.',
      confidenceTier: 'Verified',
      alternatives: [
        {
          id: 'alt-d1-1',
          title: 'Private Tea Ceremony with Master Sen at Urasenke Teahouse',
          timeSlot: 'afternoon',
          location: 'Kamigyo-ku, Kyoto',
          description: 'A quiet, unhurried two-hour dialogue and koicha thick-tea preparation in an authentic 17th-century tearoom.',
          confidenceTier: 'Team-Vetted',
          curatorEndorsement: 'Endorsed by Elena: Exceptionally contemplative if you prefer indoor stillness over temple walks.',
        },
        {
          id: 'alt-d1-2',
          title: 'Twilight Bamboo Forest Stroll at Kodai-ji Temple Courtyard',
          timeSlot: 'evening',
          location: 'Higashiyama, Kyoto',
          description: 'Lantern-lit quiet pathway reserved for Sowaka guests after evening bell toll.',
          confidenceTier: 'Team-Vetted',
          curatorEndorsement: 'A rare atmospheric alternative to an early dinner.',
        },
      ],
    },
    {
      id: 'day-2',
      dayNumber: 2,
      date: 'OCT 15, 2026',
      title: 'Oi River Gorge & The Moss Temple of Saihō-ji',
      destination: 'Kyoto • Arashiyama Gorge',
      sanctuaryName: 'Hoshinoya Kyoto',
      morningActivity: {
        time: '08:30 JST',
        title: 'Private Wooden Riverboat Transfer up the Oi River Gorge',
        location: 'Togetsukyo Pier -> Hoshinoya Kyoto',
        notes: 'Gliding along mirror-still morning water shaded by ancient maples.',
        confidenceTier: 'Verified',
      },
      afternoonActivity: {
        time: '14:00 JST',
        title: 'Koke-dera (Saihō-ji) Private Moss Garden Contemplation',
        location: 'Matsuo, Western Kyoto',
        notes: 'Sutra calligraphy copy session followed by quiet meditation across 120 varieties of living moss.',
        confidenceTier: 'Verified',
      },
      eveningActivity: {
        time: '20:00 JST',
        title: 'Riverside Terrace Charcoal Kaiseki with Chef Kubota',
        location: 'Hoshinoya Pavilion Terrace',
        notes: 'Overlooking the quiet river gorge under starlight.',
        confidenceTier: 'Verified',
      },
      curatorNote: 'The Abbot at Saihō-ji has reserved the north moss cloister for your exclusive walk.',
      confidenceTier: 'Verified',
      alternatives: [
        {
          id: 'alt-d2-1',
          title: 'Tenryu-ji Sogenchi Garden Private Morning Viewing with Chief Monk',
          timeSlot: 'morning',
          location: 'Saga Tenryuji, Ukyo Ward',
          description: 'Access the 14th-century pond garden designed by Muso Soseki before general gates open.',
          confidenceTier: 'Verified',
          curatorEndorsement: 'Perfect if you are an early riser seeking absolute stillness before morning crowds.',
        },
        {
          id: 'alt-d2-2',
          title: 'Wild Cedar Wood Carving Atelier Session with Master Sudo',
          timeSlot: 'afternoon',
          location: 'Kitayama Forest Studio',
          description: 'Two-hour sensory immersion working with Yoshino cedar shavings and traditional Japanese chisels.',
          confidenceTier: 'Team-Vetted',
          curatorEndorsement: 'A deeply tactile and calming craft encounter.',
        },
      ],
    },
    {
      id: 'day-3',
      dayNumber: 3,
      date: 'OCT 16, 2026',
      title: 'Tadao Ando Architecture & The Seto Inland Sea',
      destination: 'Naoshima • Art Island',
      sanctuaryName: 'Benesse House Oval',
      morningActivity: {
        time: '09:00 JST',
        title: 'Private Bullet Train Transfer & Chartered Catamaran to Naoshima',
        location: 'Kyoto Station -> Uno Port -> Naoshima',
        notes: 'Reserved Green Car 1st Class seating with port luggage escort.',
        confidenceTier: 'Verified',
      },
      afternoonActivity: {
        time: '14:30 JST',
        title: 'Private Guided Walk Through Chichu Art Museum & Monet Waterlilies',
        location: 'Chichu Art Museum',
        notes: 'Architectural immersion: Walter De Maria and James Turrell natural light installations.',
        confidenceTier: 'Team-Vetted',
      },
      eveningActivity: {
        time: '19:00 JST',
        title: 'Private Monorail Ascent to Benesse House Oval & Sunset Aperture',
        location: 'Benesse House Oval Terrace',
        notes: 'Panoramic sunset view over the tranquil Seto Inland Sea islands.',
        confidenceTier: 'Verified',
      },
      curatorNote: 'The museum galleries remain open 24/7 for Oval guests — take an unhurried night walk.',
      confidenceTier: 'Team-Vetted',
      alternatives: [
        {
          id: 'alt-d3-1',
          title: 'Teshima Art Museum Private Twilight Access',
          timeSlot: 'afternoon',
          location: 'Teshima Island (20 min by chartered boat)',
          description: 'Ryue Nishizawa water droplet concrete shell pavilion overlooking terraced rice paddies.',
          confidenceTier: 'Team-Vetted',
          curatorEndorsement: 'Recommended if you have already experienced Naoshima and desire architectural radicalism.',
        },
        {
          id: 'alt-d3-2',
          title: 'Sunset Sea Kayak to Honmura Forgotten Sea Caves',
          timeSlot: 'evening',
          location: 'South Coast Naoshima',
          description: 'Guided quiet paddle into secluded sea apertures with twilight bioluminescence.',
          confidenceTier: 'General',
          curatorEndorsement: 'Weather-dependent; suitable for calm tides.',
        },
      ],
    },
    {
      id: 'day-4',
      dayNumber: 4,
      date: 'OCT 17, 2026',
      title: 'Thermal Mineral Springs & Kerry Hill Cedar Pavilions',
      destination: 'Ise-Shima • Ago Bay',
      sanctuaryName: 'Amanemu',
      morningActivity: {
        time: '10:00 JST',
        title: 'Scenic Coastal Transfer to Ago Bay Sanctuary',
        location: 'Naoshima -> Ise-Shima National Park',
        notes: 'Private vehicle through the forested peninsula to the Kerry Hill pavilions.',
        confidenceTier: 'Verified',
      },
      afternoonActivity: {
        time: '15:00 JST',
        title: 'Watsu Aquatic Therapy & Thermal Mineral Onsen Bathing',
        location: 'Amanemu Onsen Pavilion',
        notes: 'Therapeutic saltwater mineral soak fed directly by regional underground hot springs.',
        confidenceTier: 'Verified',
      },
      eveningActivity: {
        time: '19:30 JST',
        title: 'Seven-Seat Omakase with Chef Sato Overlooking Ago Bay',
        location: 'Amanemu Private Dining Terrace',
        notes: 'Featuring local Ise spiny lobster and Matsusaka wagyu beef prepared over binchotan charcoal.',
        confidenceTier: 'Verified',
      },
      curatorNote: 'Your final evening is designed for deep physical restoration and coastal stillness.',
      confidenceTier: 'Verified',
      alternatives: [
        {
          id: 'alt-d4-1',
          title: 'Private Ama Diver Wooden Hut Lunch & Fresh Seafood Hearth',
          timeSlot: 'afternoon',
          location: 'Osatsu Village, Toba Coast',
          description: 'Dialogue with third-generation female free-divers over abalone roasted on an open charcoal fire.',
          confidenceTier: 'Verified',
          curatorEndorsement: 'An unforgettable cultural encounter with one of Japan’s oldest oceanic traditions.',
        },
        {
          id: 'alt-d4-2',
          title: 'Ise Jingu Grand Shrine Inner Naiku Sanctuary Private Dawn Walk',
          timeSlot: 'morning',
          location: 'Ise Grand Shrine (30 min transfer)',
          description: 'Walk through 800-year-old Japanese cedar forests to Japan’s holiest Shinto sanctuary.',
          confidenceTier: 'Verified',
          curatorEndorsement: 'Highest spiritual reverence; best experienced in the silent mist of early dawn.',
        },
      ],
    },
  ],
};

export const SEED_TASTE_PROFILE: TasteProfile = {
  id: 'taste-julian-sterling',
  pace: 'unhurried',
  architecturalPurity: 9,
  stillnessIndex: 10,
  culinaryFocus: 'counter-omakase',
  preferredRealms: ['Kyoto', 'Naoshima', 'Ise-Shima'],
  archetypeTitle: 'The Contemplative Minimalist',
  archetypeDescription: 'You seek journeys devoid of spectacle — drawn instead to raw cedar, meditative gardens, water courtyards, and hyper-intimate culinary mastery.',
  writtenPortrait: 'You tend to linger — slow mornings, private courtyards, and uninterrupted daylight.',
  matchedSanctuaries: ['amanemu', 'benesse-house', 'sowaka'],
  createdAt: Date.now(),
};
